version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow

  webserver:
    image: apache/airflow:2.1.2
    depends_on:
      - postgres
    environment:
      - AIRFLOW_DATABASE_URL=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__RBAC=true
    ports:
      - "8090:8080"